title: "Nathan Heller"
description: "Nathan's notes."
url: "https://notes.hellbhoy.net"
source: ./notes
theme: minima
minima:
  skin: solarized

include:
  - _why.md


header_pages:
  - books.md
  - misc.md
  - projects.md
  - writing.md
  - software.md
  - resume.md

plugins:
  - jekyll-default-layout
  - jekyll-wikirefs
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
